name: Daily ETL Job

on:
  schedule:
    - cron: '30 20 * * *'  # Runs every day at 2:00 AM IST (UTC+5:30)
  workflow_dispatch:  # Optional: lets you manually trigger the workflow

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests pandas psycopg2-binary

      - name: Run ETL Script
        run: python your_script.py  # Replace with your script file name
